name: SkyPoint Studios
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8637831422965974
title: 'SkyPoint Studios is a Web Design Company Billings, Montana'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#006fc1'
    - '#111113'
    - '#7aafd7'
    - '#d1dae3'
    - '#786a61'
  brandStrength: 0
  lightness: 0.8164556312840432
  saturation: 0.23356972564943135
  rhythmicContrast: 0.18435863475315273
purpose: []
