name: SkyPoint Studios
favicon: null
layout_spectrum: 0.2765349675901234
typography_spectrum: 0.8637831422965974
title: 'Web Design Company Billings, Montana'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7377381981350482
  lightness: 0.8164556312840432
  saturation: 0.23356972564943135
  rhythmicContrast: 0.18435863475315273
purpose: []
